[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "AylluIoT"
version = "1.0.0"
description = "Python Library to run an IoT system."
readme = "README.md"
