name: Pytest PR Pipeline

on:
  pull_request:
    branches:
      - main
      - dev

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'testing' 
        type: choice
        options:
        - testing
        - warning
        - debug
      tags:
        description: 'Workflow execution tags'
        required: true 
        type: string
      branch:
        description: 'Execution Branch'
        required: true
        default: 'dev'
        type: string
      
jobs:
  testing:
    name: Tox Testing Pipeline
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
    steps:
    - name: Set working branch
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
